GLOBAL IniVersion ini73c-test
GLOBAL ActiveConfigOnStartup 1
GLOBAL StartInTraybar 
#GLOBAL capsicainOnOffKey SCRLOCK
#GLOBAL DebugOnStartup

[CONFIG_1]
OPTION ConfigName EDUUH_MOD
INCLUDE LAYOUT_EDUUH_MOD
INCLUDE EDUUH_ALL_SECTION

[EDUUH_ALL_SECTION]
INCLUDE MODS_REMAPPING
INCLUDE EDUUH_NUMPAD
INCLUDE EDUUH_ARROW_KEYS
INCLUDE EDUUH_SYMBOLS
INCLUDE POWER_TAB_MODE
INCLUDE EDUUH_TOP-ROW
InCLUDE EDUUH_SINGLE_KEYS


[MODS_REMAPPING]
# MOD KEY ASSIGNMENTS:
#
# +--------+--------+--------+--------+--------+--------+
# |  LWIN  |  LALT  |  LCTRL |  CAPS  |  LSHFT |  RSHFT |
# |    |   |    |   |    |   |    |   |    |   |    |   |
# |    v   |    v   |    v   |    v   |    v   |    v   |
# | MOD13  | MOD12  | MOD13  |  LSHFT | LCTRL  | RCTRL  |
# +--------+--------+--------+--------+--------+--------+
#
# +--------+--------+--------+
# |  RCTRL |  RET   |  RALT  |
# |    |   |    |   |    |   |
# |    v   |    v   |    v   |
# | PRINT  | RSHFT  | MOD11  |
# +--------+--------+--------+
#
# MOD11: Activated by RALT/PRINT - Numpad mode
# MOD12: Activated by LALT      - Arrows & Symbols mode
# MOD13: Activated by LCTRL/LWIN - Tab & Brackets mode
#
#          Key     To Key     (IfTapped) (IfTap+Hold)
#REWIRE     LALT    MOD12       //         LALT  
REWIRE  LSHF LCTRL
REWIRE  RSHF RCTRL
REWIRE  RET RSHF
REWIRE CAPS LSHF  
REWIRE  LALT MOD12  
REWIRE  RALT MOD11    
REWIRE LCTRL MOD13
REWIRE RCTRL PRINT   
REWIRE PRINT MOD11
REWIRE LWIN  LALT

[LAYOUT_EDUUH_MOD]
# COLEMAK-DH LAYOUT:
#
# QWERTY Layout (ALPHA_FROM):
# +----+----+----+----+----+    +----+----+----+----+----+----+----+----+
# | Q  | W  | E  | R  | T  |    | Y  | U  | I  | O  | P  | [  | ]  | \  |
# +----+----+----+----+----+    +----+----+----+----+----+----+----+----+
#   +----+----+----+----+----+    +----+----+----+----+----+----+----+
#   | A  | S  | D  | F  | G  |    | H  | J  | K  | L  | ;  | '  |
#   +----+----+----+----+----+    +----+----+----+----+----+----+----+
#     +----+----+----+----+----+    +----+----+----+----+----+
#     | Z  | X  | C  | V  | B  |    | N  | M  | ,  | .  | /  |
#     +----+----+----+----+----+    +----+----+----+----+----+
#
# Colemak-DH Layout (ALPHA_TO):
# +----+----+----+----+----+    +----+----+----+----+----+----+----+----+
# | Q  | W  | F  | P  | G  |    | V  | J  | L  | U  | Y  | ;  | '  | =  |
# +----+----+----+----+----+    +----+----+----+----+----+----+----+----+
#   +----+----+----+----+----+    +----+----+----+----+----+----+----+
#   | A  | R  | S  | T  | D  |    | /  | K  | N  | E  | I  | O  |
#   +----+----+----+----+----+    +----+----+----+----+----+----+----+
#     +----+----+----+----+----+    +----+----+----+----+----+
#     | X  | C  | B  | V  | -  |    | Z  | M  | H  | ,  | .  |
#     +----+----+----+----+----+    +----+----+----+----+----+
#
ALPHA_FROM
   q  w  e  r  t     y  u  i  o  p [ \
    a  s  d  f  g     h  j  k  l  ; '  
     z  x  c  v  b     n  m ,  . / 
ALPHA_TO
   q  w  f  p  g     v j  l  u  y  ; =
    a  r  s  t  d    / k  n  e  i  o
     x  c  b v -    z  m  h , . 
ALPHA_END


[EDUUH_SYMBOLS]
# [MOD12 SYMBOLS] (Activated by LALT)
# Left-hand symbol layer:
#
# +-----+-----+-----+-----+-----+
# |  @  |  ~  |  <  |  >  |  ^  |
# | (Q) | (W) | (E) | (R) | (T) |
# +-----+-----+-----+-----+-----+
#   +-----+-----+-----+-----+-----+
#   |  \  | ESC |  9  |  !  |  ?  |
#   | (A) | (S) | (D) | (F) | (G) |
#   +-----+-----+-----+-----+-----+
#     +-----+-----+-----+-----+
#     |  *  |  `  |  &  |  |  |
#     | (Z) | (X) | (C) | (V) |
#     +-----+-----+-----+-----+
#
COMBO  Q   [... .&.. .... ....] > moddedKey(2 + .... .... ...&) # @
COMBO  W   [... .&.. .... ....] > moddedKey(` + .... .... ...&) # ~
COMBO  E   [... .&.. .... ....] > key(, + .... .... ...&) # <
COMBO  R  [... .&.. .... ....] > key(. + .... .... ...&) # >
COMBO  T  [... .&.. .... ....] > moddedKey(6 + .... .... ...&) # ^
COMBO  Z  [... .&.. .... ....] > moddedKey(8 + .... .... ...&) # ^
COMBO  X  [... .&.. .... ....] > key(`) # `
COMBO  C  [... .&.. .... ....] > moddedKey(7 + .... .... ...&) # ^
COMBO  V  [... .&.. .... ....] > moddedKey(\ + .... .... ...&) # ^
COMBO  A  [... .&.. .... ....] > key(\) # \
COMBO  S  [... .&.. .... ....] > key(ESC) 
COMBO  D  [... .&.. .... ....] > key(9) # ^           
COMBO  F [... .&.. .... ....] > moddedKey(1 + .... .... ...&) # !
COMBO  G  [... .&.. .... ....] > moddedKey(/ + .... .... ...&) # ?

[EDUUH_TOP-ROW]
# TOP ROW REMAPPING (Standard state - no modifiers active)
#
# +-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
# |  ?  |  !  |  [  |  ]  |  "  |  {  |  }  |  *  |  /  |  '  |  )  |  (  |  +  |
# | (`) | (1) | (2) | (3) | (4) | (5) | (6) | (7) | (8) | (9) | (0) | (-) | (=) |
# +-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
#
COMBO `  [... .... .... ....] > moddedKey(/ + .... .... ...&) # ?
COMBO 1  [... .... .... ....] > moddedKey(1 + .... .... ...&) # ?
COMBO 2  [... .... .... ....] > key([) # [
COMBO 3  [... .... .... ....] > key(]) # ]
COMBO 4  [... .... .... ....] > moddedKey(' + .... .... ...&) # "
COMBO 5  [... .... .... ....] > moddedKey([ + .... .... ...&) # {
COMBO 6  [... .... .... ....] > moddedKey(] + .... .... ...&) # }
COMBO 7  [... .... .... ....] > moddedKey(8 + .... .... ...&) # *
COMBO 8  [... .... .... ....] > key(/) # *
COMBO 9  [... .... .... ....] > key(') # '
COMBO 0  [... .... .... ....] > moddedKey(0 + .... .... ...&) # )
COMBO -  [... .... .... ....] > moddedKey(9 + .... .... ...&) # (
COMBO =  [... .... .... ....] > moddedKey(= + .... .... ...&) # +

[EDUUH_SINGLE_KEYS]
# SINGLE KEY REMAPPING (Standard state - no modifiers active)
#
# +-----+
# |  +  |
# | (') |
# +-----+
#
COMBO ] [... .... .... ....] > moddedKey(; + .... .... ...&) #

[EDUUH_NUMPAD]
# [MOD11 NUMPAD] (Activated by RALT or PRINT)
# Right-hand numpad layer:
#
#                     Number Row:
#                     +-----+-----+-----+
#                     |  7  |  8  |  9  |
#                     | (9) | (0) | (-) |
#                     +-----+-----+-----+
#
# +-----+-----+-----+
# |  4  |  5  |  6  |
# | (I) | (O) | (P) |
# +-----+-----+-----+
#   +-----+-----+-----+-----+
#   |  1  |  2  |  3  |  0  |
#   | (K) | (L) | (;) | (') |
#   +-----+-----+-----+-----+
#     +-----+-----+-----+
#     |  $  |  %  |  #  |
#     | (N) | (M) | (,) |
#     +-----+-----+-----+
#
COMBO  N   [... &... .... ....] > moddedKey(4 + .... .... ...&) # $
COMBO  M   [... &... .... ....] > moddedKey(5 + .... .... ...&) # %
COMBO  ,   [... &... .... ....] > moddedKey(3 + .... .... ...&) # #
#COMBO  ,   [... &... .... ....] > key(2)
#COMBO  .   [... &... .... ....] > key(3)
#  Home Row
COMBO  J   [... &... .... ....] > key(\) # 
COMBO  K   [... &... .... ....] > key(1) # 1
COMBO  L   [... &... .... ....] > key(2) # 2
COMBO  ;   [... &... .... ....] > key(3) # 3
COMBO  '   [... &... .... ....] > key(0) # 0
# Top Row
COMBO  I   [... &... .... ....] > key(4) # 4
COMBO  O   [... &... .... ....] > key(5) # 5 
COMBO  P   [... &... .... ....] > key(6) # 6
# Number Row
COMBO 9  [... &... .... ....] > key(7) # 7
COMBO 0  [... &... .... ....] > key(8) # 8
COMBO -  [... &... .... ....] > key(9) # 9

[EDUUH_ARROW_KEYS]
# [MOD12 ARROWS] (Activated by LALT)
# Right-hand arrow key layer:
#
#                 +-----+
#                 |  ↑  |
#                 | (O) |
#                 +-----+
# +------+------+------+-------+
# |  ←   |  ↓   |  →   | ENTER |
# | (K)  | (L)  | (;)  |  (')  |
# +------+------+------+-------+
#
COMBO  K  [... .&.. .... ....] > key(LEFT)
COMBO  '   [... .&.. .... ....] > key(RET) 
COMBO  L   [... .&.. .... ....] > key(DOWN) 
COMBO  ;  [... .&.. .... ....] > key(RIGHT) 
COMBO  O   [... .&.. .... ....] > key(UP)

[POWER_TAB_MODE]
# [MOD13 TAB & BRACKETS] (Activated by LCTRL or LWIN)
# Right-hand special characters & tab mode:
#
# +-----+
# |  /  |
# | (I) |
# +-----+
#   +------+-----+-----+-----+
#   | TAB  |  (  |  {  |  [  |
#   | (J)  | (K) | (L) | (;) |
#   +------+-----+-----+-----+
#     +-----+-----+
#     |  )  |  }  |
#     | (,) | (.) |
#     +-----+-----+
#
COMBO  J  [..& .... .... ....] > key(TAB)
COMBO  K  [..& .... .... ....] > moddedKey(9 + .... .... ...&) # (
COMBO  ,  [..& .... .... ....] > moddedKey(0 + .... .... ...&) # )
COMBO  L  [..& .... .... ....] > moddedKey([ + .... .... ...&) # { 
COMBO  .  [..& .... .... ....] > moddedKey(] + .... .... ...&) # } 
COMBO  ;  [..& .... .... ....] > key([) 
COMBO  I  [..& .... .... ....] > key(/)

[ahk]
# KEYBOARD LAYOUT SUMMARY:
#
# Base:         Colemak-DH layout with remapped modifiers;
# MOD11 (RALT): Numpad layer (right hand)
# MOD12 (LALT): Arrow keys (right hand) and Symbols (left hand)
# MOD13 (LCTRL): Tab, brackets, and special chars (right hand)
# Top Row:      Number keys remapped to symbols
#
Persistent