GLOBAL IniVersion ini73c-test
GLOBAL ActiveConfigOnStartup 1
GLOBAL StartInTraybar 
GLOBAL capsicainOnOffKey SCRLOCK
GLOBAL DebugOnStartup

[CONFIG_1]
OPTION ConfigName EDUUH_MOD
INCLUDE LAYOUT_EDUUH_MOD
INCLUDE EDUUH_ALL_SECTION  

[EDUUH_ALL_SECTION]
INCLUDE MODS_REMAPPING
INCLUDE EDUUH_NUMPAD
INCLUDE EDUUH_ARROW_KEYS
INCLUDE EDUUH_SYMBOLS
INCLUDE POWER_TAB_MODE


[MODS_REMAPPING]
#          Key     To Key     (IfTapped) (IfTap+Hold)
#REWIRE     LALT    MOD12       //         LALT  
REWIRE  LSHF LCTRL
REWIRE  RSHF LCTRL
REWIRE  RET RSHF
REWIRE CAPS LSHF
REWIRE  LALT   MOD12  
REWIRE  RALT   MOD11  
REWIRE TAB MOD13
REWIRE LCTRL CAPS
 # '//' means "don't process this optional thing"; in this case, tapped LALT does nothing

[LAYOUT_EDUUH_MOD]
ALPHA_FROM
   q  w  e  r  t     y  u  i  o  p [ ] \
    a  s  d  f  g     h  j  k  l  ; '  
     z  x  c  v  b     n  m ,  . / 
ALPHA_TO
   q  w  f  p  g     NOP j  l  u  y  ; ' =
    a  r  s  t  d     RET k  n  e  i  o
     x  c  b  v  -   z  m  h ,  . 
ALPHA_END

[EDUUH_SYMBOLS]
# [MOD11 SYMBOLS]
# summons the Numpad under the Left hand.
# TAB  @ ~ [ ] ^   
#      \ ESC …  ! ?   
#      * ` &  | - 
COMBO  Q   [... .&.. .... ....] > moddedKey(2 + .... .... ...&) # @
COMBO  W   [... .&.. .... ....] > moddedKey(` + .... .... ...&) # ~
COMBO  E   [... .&.. .... ....] > key([) # [
COMBO  R  [... .&.. .... ....] > key(]) # ]
COMBO  T  [... .&.. .... ....] > moddedKey(6 + .... .... ...&) # ^
COMBO  Z  [... .&.. .... ....] > moddedKey(8 + .... .... ...&) # ^
COMBO  X  [... .&.. .... ....] > key(`) # `
COMBO  C  [... .&.. .... ....] > moddedKey(7 + .... .... ...&) # ^
COMBO  V  [... .&.. .... ....] > moddedKey(\ + .... .... ...&) # ^
COMBO  A  [... .&.. .... ....] > key(\) # \
COMBO  S  [... .&.. .... ....] > key(ESC) 
COMBO  D  [... .&.. .... ....] > key(9) # ^           
COMBO  F [... .&.. .... ....] > moddedKey(1 + .... .... ...&) # !
COMBO  G  [... .&.. .... ....] > moddedKey(/ + .... .... ...&) # ?

[EDUUH_NUMPAD]
# [MOD11 Config]
# summons the Numpad under the right hand.
# …  … … … … …    -  +  7  8  9  #  
#      … … … …  …    % BS  5  6  0  =
#      … … …  …  …    $ 1  2  3  /
COMBO  M   [... &... .... ....] > key(1)
COMBO  ,   [... &... .... ....] > key(2)
COMBO  .   [... &... .... ....] > key(3)
COMBO  /   [... &... .... ....] > key(/)
COMBO  J   [... &... .... ....] > moddedKey(5 + .... .... ...&) # %
COMBO  U   [... &... .... ....] > moddedKey(= + .... .... ...&) # +
COMBO  N   [... &... .... ....] > moddedKey(4 + .... .... ...&) # $
COMBO  RET  [... &... .... ....] > key(=) 

COMBO  I   [... &... .... ....] > key(7) 
COMBO  O   [... &... .... ....] > key(8) 
COMBO  P   [... &... .... ....] > key(9) 
COMBO  [   [... &... .... ....] > moddedKey(3 + .... .... ...&) # #

COMBO  K  [... &... .... ....] > key(BSP)
COMBO  L   [... &... .... ....] > key(5) 
COMBO  ;  [... &... .... ....] > key(6) 
COMBO  '  [... &... .... ....] > key(0)

[EDUUH_ARROW_KEYS]
# MOD12 Config
# summons the Arrow keys under the right hand.
# [MOD11 Config]
# summons the Numpad under the right hand.
#   q  w  e  r  t     y  u  i  o  p [  
#    a  s  d  f  g     h  j  k  l  ; '  
#     z  x  c  v  b    n  m ,  . / 

# TAB  … … … … …    -  …  …  8 … … …  …
#      … … …  …  …     …  5  6  0  …
#      …  …  …  …  …     +  …  …  … 
COMBO  K  [... .&.. .... ....] > key(LEFT)
COMBO  '   [... .&.. .... ....] > key(RET) 
COMBO  L   [... .&.. .... ....] > key(DOWN) 
COMBO  ;  [... .&.. .... ....] > key(RIGHT) 
COMBO  O   [... .&.. .... ....] > key(UP)

[POWER_TAB_MODE]
# MOD13  … … … … …    -  …  …  8 … … …  …
#        … … …  …  …     TAB (  {  [
#         …  …  …  …     +  …  )  } ]

COMBO  J  [..& .... .... ....] > key(TAB)
COMBO  K  [..& .... .... ....] > moddedKey(9 + .... .... ...&) # (
COMBO  L  [..& .... .... ....] > moddedKey([ + .... .... ...&) # { 
COMBO  ;  [..& .... .... ....] > key([) # [


# COMBO  '  [..& .... .... ....] > key(0)

[ahk]
Persistent