GLOBAL IniVersion ini73c-test
GLOBAL ActiveConfigOnStartup 1
GLOBAL StartInTraybar 
GLOBAL capsicainOnOffKey SCRLOCK
GLOBAL DebugOnStartup


[CONFIG_1]
OPTION ConfigName Colemak_MOD
INCLUDE LAYOUT_COLEMAK_MOD

[LAYOUT_COLEMAK_MOD]
ALPHA_FROM
   q  w  e  r  t     y  u  i  o  p [  
    a  s  d  f  g     h  j  k  l  ; '  
     z  x  c  v  b     n  m ,  . / 
ALPHA_TO
   q  w  f  p  g     NOP j  l  u  y  ; 
    a  r  s  t  d     NOP k  n  e  i  o
     x  c  b  v  NOP   z  m  h ,  . 
ALPHA_END

# modifiers

COMBO  LSHF   [.... ...& ....] > key(CAPSOFF)  #[RSHIFT] + [LSHIFT] = ShiftLock OFF.
COMBO  RSHF   [.... .... ...&] > key(CAPSON)   #[LSHIFT] + [RSHIFT] = ShiftLock ON.

REWIRE     LALT    MOD12  //  LALT
REWIRE     RALT    MOD10  //  RALT

# Load AutoHotkey_H 2.0+ as DLL and call AHK cryptic hotkeys if you really want to)
# Get AutoHotkey64.dll from https://github.com/thqby/AutoHotkey_H and put next to capsicain.exe LOBAL startAHK

# Everything after [ahk] will be loaded as an AHK script and reloaded on Esc+A/R
# This has to be the last section in the ini
[ahk]
Persistent
